import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Films from '../components/Films'
import { useState, useEffect } from 'react'
import { TextField, 
          Button} from '@material-ui/core'

const defaultEndpoint = 'http://localhost:3000/api/films'

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint);
  const data = await res.json();
  return {
    props: {
      data
    }
  }
}

export default function Home({ data }) {
  const [search, setSearch] = useState('');
  const [ghibli, setGhibli] = useState(data.results);

  useEffect(() => {
    let res = [];
    if(data.length != 0) {
      data.results.filter((datu) => {
        datu.title.toLowerCase().match(search.toLowerCase()) && (
          res.push(datu)
        )
      })
      setGhibli(res)
    }

  }, [search, data]);

  function onHandleChange(e) {
    setSearch(e.target.value)
  }

  function handleOnSubmitSearch(e) {
    e.preventDefault();
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
            <Image src="/studio_ghibli.png" 
              alt="studio ghibli"
              height="100px"
              width="200px" />
        </h1>

        <div>
          <form onSubmit={handleOnSubmitSearch}>
            <TextField style={{ "marginRight": "5px"}} 
              type="search" 
              name="query"
              label="What are we looking for?"
              onChange={onHandleChange}
            />
            <Button 
              variant="outlined"
              style={{"marginTop": "10px"}}
              >
                Search
            </Button>
          </form>
        </div>

        <Films films={ghibli} />

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
